Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../../ansible/playbooks/install_docker.yml"
    ansible.groups = {"web" => "default"}
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../../ansible/playbooks/deploy_app.yml"
    ansible.groups = {"web" => "default"}
  end
end
