Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../../ansible/playbooks/install_docker.yml"
    ansible.groups = {"web" => "default"}
  end
end
