#cloud-config
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDkjAZ3omHKEPzfkeQ72Hk/in6F5iSS3J+FKatXhyCMkT1pz90OLjiHuEiYJ4eJM3Fc2I4pOsrKKeYL+iKFaX3U41A+SGnOQrty/3tqkiTNHbqGzIWhCduEybt4cMs1JX9sb2PI4qLMqxlGxB9CQf6yYLshcU2l6sk4D1xKUgO+eMmuvRXYF76/uvby3txvLT2JylsgLeVRyl//FTFCIdx7qb0Q93glz71liuoUAwgVD8TkCqBAjMZH6kk9rzLbuqMIm6X6syrBOcXb6nk5zH4yQEZJB8Et+B3qR4yBJ+edh5CX4J15MsrHxAYJBgGCTNljWYzB1xAIVXrxbyH3D4UMQLlzVIAOPIGtyc39cEOSbgyryLvxhoodQ/Hk/9PPxxETFAy1P931OOTZymYl8lFnG/QMBaZEth+sAuQKWYFfiulExbBOdMpDHbDJbXVE/VRYHGsuyt7WhBV9m6QcptvWgfMyrQNgS/TNmiutGa+CWe/N8Y93NFfkh9gZTO30f38= a1d4r@yandex.ru

# runcmd:
#   - sudo apt-get update