version: "3"

networks:
  monitoring:

services:
  web:
    image: a1d4r/devops-python-app:latest
    ports:
      - "8000:8000"
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - ./promtail.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"