password: ENC[AES256_GCM,data:rBG7JXq5fJF6v1HFyCerZgdwLw==,iv:I6ydVokBfJDdIi98WqIyWqgLlr4Pp+VRW9IC5eKEI6s=,tag:P/BEEzgvm+h+mLKJ3coRqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-26T19:57:13Z"
    mac: ENC[AES256_GCM,data:cgDQEEVe06n29mNP/W/jjc6lMC+H6r8irj+ITgUZtXyq8gJ/8XStf61hN9474H0hj6blop3GRgJOdP5oWfUBYzY3oyRtwNVKolaCX1KB570X8s30ezPSSqGfFZLC+sCVYZC4hC5DtjCIrCM8zFgf7cj+7ZE+9tDsdCq3+2KiphE=,iv:WcK0nA4s871aLiAc5N1vaat5I+DVP9CFQuwB/8lsny8=,tag:arS1EPNHMRU2AqpOEPJ/BA==,type:str]
    pgp:
        - created_at: "2021-09-26T19:53:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAzlqKiMvQhQCAQwAi3nHCyp34qgek7nWOkO/bL2zGqS6WDY3p61sPXPSdSQ0
            Tc3xhZ3+aRdG0PC1+Z7SpUXmK0d5o4EAmzmU4PH4S1JiczLHzMF+wyp6/0yTpmVz
            jeEdF/7Jl4cxlIgOfgEwWKjs5WWpMXelw6R1GWQTIJ6hU2wGEwiI4KH1I0wgb0Yt
            Vuf3ZmQEtFcTF9pCtLTzgMG0uRa4569MddMHPfELyGdTY3kvFdJbFiprl9I314ZG
            ttipjzsIFiqDUCPANFw3YV8sXVTrRuqTpRMMCPnUOE7WvOWGfFL5+LPr4HTgMsbB
            zBr+UAAQxDdlXbBgHu4x+saLKa0qk4zEXHOFr4Muhv2VaPkYdql1Gu1fyu9rCeB/
            /RIb7fUUs00hsdqCRn8VJxvdCpuDQ5zwy38xMvqToJU3rfWpPEkBjIyZddfCj6ea
            0oZ3tHsvSsB3Sh5dNdZ1tF8j8KfS8gqPXtrru1e3Z+q0VOrRecrxhN5iG81Mojmt
            Pbo9M341e0wu6a2B6tDd0l4BubG59CZGi/9Q/If5337WtdMcX8E7JF2f/N/FBW9j
            yEueebx0VTp36TMZUUsSCJEYEkGDu5w6yqQQDrme4/jJvD14nz2bxBB+bPv4crnv
            UjofHk8qie9Uh0jSxZJt
            =lU1s
            -----END PGP MESSAGE-----
          fp: 01906A275FB28318E20E633DD56898708EE9181F
    unencrypted_suffix: _unencrypted
    version: 3.7.1
