kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.config.configMapName }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
data:
  config.json: |-
{{ .Files.Get "config.json" | indent 4 }}