apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}