name: Python web application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app_python

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      run:
        pip install poetry==1.1.8
    - name: Install dependencies
      run:
        poetry install --no-root
    - name: Display installed packages
      run:
        poetry show