name: Python web application

on: [push]

env:
  APP_PATH: ./app_python  # source root
  CODE: app tests  # packages with source code (inside source root)
  TESTS: tests  # package with tests (inside source root)
  IMAGE_NAME: devops-python-app  # name for docker image

jobs:

  lint_test:  # Run linters and test application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.APP_PATH }}

    steps:
    - name: Checkout Github repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1.1.8
      with:
        version: 1.1.8
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root
        poetry run mypy --install-types --namespace-packages --explicit-package-bases --non-interactive ${{ env.CODE }}
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    - name: Activate environment
      run: source .venv/bin/activate
    - name: Check codestyle
      run: |
        isort --diff --check-only --settings-path pyproject.toml ${{ env.CODE }}
        black --diff --check --config pyproject.toml ${{ env.CODE }}
        darglint --verbosity 2 ${{ env.CODE }}
    - name: Run linters
      run: |
        pylint --rcfile=.pylintrc ${{ env.CODE }}
        mypy --config-file pyproject.toml --namespace-packages --explicit-package-bases ${{ env.CODE }}
    - name: Check safety
      run: |
        poetry check 
        safety check --full-report
        bandit -s B101 --recursive ${{ env.CODE }}
    - name: Run tests
      run: |
        python -m pytest --cov=app ${{ env.TESTS }}
  
  build:  # Build docker image and push it to Dockerhub
    needs: lint_test
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'

    defaults:
      run:
        working-directory: ./app_python

    steps:
    - name: Checkout Github repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.APP_PATH }}
        file: ${{ env.APP_PATH }}/docker/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
